export const deeplink = [
  {
    code: "marketplace",
    id: 1,
    title: "Витрина",
    availableVersion: "0.0",
    platforms: [ "iOS", "Android" ],
    path: "pfm/marketplace",
  },
  {
    code: "submarketplace",
    id: 2,
    title: "Подвитрины",
    availableVersion: "0.0",
    platforms: [ "iOS", "Android" ],
    path: "pfm/marketplace",
  },
  {
    code: "services",
    id: 3,
    title: "Сервисы",
    availableVersion: "0.0",
    platforms: [ "iOS", "Android" ],
    path: "",
  },
  {
    code: "selection",
    id: 4,
    title: "Подборки",
    availableVersion: "0.0",
    platforms: [ "iOS", "Android" ],
    path: "pfm/marketplace",
  },
  {
    code: "categories",
    id: 5,
    title: "Категории",
    availableVersion: "0.0",
    platforms: [ "iOS", "Android" ],
    path: "pfm/marketplace",
  },
  {
    code: "pif",
    id: 6,
    title: "Продукты ПИФ",
    availableVersion: "0.0",
    platforms: [ "iOS", "Android" ],
    path: "welfare/invest-pif/product",
  },
  {
    code: "trust",
    id: 7,
    title: "Готовые стратегии",
    availableVersion: "0.0",
    platforms: [ "iOS", "Android" ],
    path: "investments/tm/product/card",
  },
  {
    code: "zpif",
    id: 8,
    title: "ЗПИФ",
    availableVersion: "0.0",
    platforms: [ "iOS", "Android" ],
    path: "pfm/marketplace",
  },
  {
    code: "pension",
    id: 9,
    title: "Пенсионные продукты",
    availableVersion: "0.0",
    platforms: [ "iOS", "Android" ],
    path: "",
  },
  {
    code: "iis",
    id: 10,
    title: "Продукты ИИС",
    availableVersion: "0.0",
    platforms: [ "iOS", "Android" ],
    path: "investments/tm/product/card",
  },
  {
    code: "nszh",
    id: 11,
    title: "НСЖ",
    availableVersion: "0.0",
    platforms: [ "iOS", "Android" ],
    path: "pfm/marketplace",
  },
  {
    code: "otherProducts",
    id: 12,
    title: "Другие продукты",
    availableVersion: "0.0",
    platforms: [ "iOS", "Android" ],
    path: "pfm/marketplace",
  },
  {
    code: "marketplaceWeb",
    id: 13,
    title: "Основная витрина",
    availableVersion: "0.0",
    platforms: [ "web" ],
    path: "",
  },
]