export const deeplink = [
  {
    code: "marketplace",
    id: 1,
    title: "Витрина",
    availableVersionFrom: "0.0",
    availableVersionTo: "99.99",
    platforms: [ "iOS", "Android", "iOS SBOL" ],
    path: "pfm/marketplace",
  },
  {
    code: "submarketplace",
    id: 2,
    title: "Подвитрины",
    availableVersionFrom: "0.0",
    availableVersionTo: "99.99",
    platforms: [ "iOS", "Android", "iOS SBOL" ],
    path: "pfm/marketplace",
  },
  {
    code: "services",
    id: 3,
    title: "Сервисы",
    availableVersionFrom: "0.0",
    availableVersionTo: "99.99",
    platforms: [ "iOS", "Android", "iOS SBOL" ],
    path: "",
  },
  {
    code: "selection",
    id: 4,
    title: "Подборки",
    availableVersionFrom: "0.0",
    availableVersionTo: "99.99",
    platforms: [ "iOS", "Android", "iOS SBOL" ],
    path: "pfm/marketplace",
  },
  {
    code: "categories",
    id: 5,
    title: "Категории",
    availableVersionFrom: "0.0",
    availableVersionTo: "14.5",
    platforms: [ "iOS", "Android" ],
    path: "pfm/marketplace",
  },
  {
    code: "pif",
    id: 6,
    title: "Продукты ПИФ",
    availableVersionFrom: "0.0",
    availableVersionTo: "99.99",
    platforms: [ "iOS", "Android", "iOS SBOL" ],
    path: "welfare/invest-pif/product",
  },
  {
    code: "trust",
    id: 7,
    title: "Готовые стратегии",
    availableVersionFrom: "0.0",
    availableVersionTo: "99.99",
    platforms: [ "iOS", "Android", "iOS SBOL" ],
    path: "investments/tm/product/card",
  },
  {
    code: "zpif",
    id: 8,
    title: "ЗПИФ",
    availableVersionFrom: "0.0",
    availableVersionTo: "99.99",
    platforms: [ "iOS", "Android", "iOS SBOL" ],
    path: "pfm/marketplace",
  },
  {
    code: "pension",
    id: 9,
    title: "Пенсионные продукты",
    availableVersionFrom: "0.0",
    availableVersionTo: "14.5",
    platforms: [ "iOS", "Android" ],
    path: "",
  },
  {
    code: "iis",
    id: 10,
    title: "Продукты ИИС",
    availableVersionFrom: "0.0",
    availableVersionTo: "99.99",
    platforms: [ "iOS", "Android", "iOS SBOL" ],
    path: "investments/tm/product/card",
  },
  {
    code: "nszh",
    id: 11,
    title: "НСЖ",
    availableVersionFrom: "0.0",
    availableVersionTo: "99.99",
    platforms: [ "iOS", "Android", "iOS SBOL" ],
    path: "pfm/marketplace",
  },
  {
    code: "otherProducts",
    id: 12,
    title: "Другие продукты",
    availableVersionFrom: "0.0",
    availableVersionTo: "99.99",
    platforms: [ "iOS", "Android", "iOS SBOL" ],
    path: "pfm/marketplace",
  },
  {
    code: "marketplaceWeb",
    id: 13,
    title: "Основная витрина",
    availableVersionFrom: "0.0",
    availableVersionTo: "99.99",
    platforms: [ "web" ],
    path: "",
  },
  {
    code: "submarketplaceWeb",
    id: 14,
    title: "Подвитрины",
    availableVersionFrom: "0.0",
    availableVersionTo: "99.99",
    platforms: [ "web" ],
    path: "",
  },
  {
    code: "servicesWeb",
    id: 15,
    title: "Сервисы",
    availableVersionFrom: "0.0",
    availableVersionTo: "99.99",
    platforms: [ "web" ],
    path: "",
  },
  {
    code: "selectionWeb",
    id: 16,
    title: "Подборки",
    availableVersionFrom: "0.0",
    availableVersionTo: "99.99",
    platforms: [ "web" ],
    path: "",
  },
  {
    code: "trustWeb",
    id: 17,
    title: "Готовые стратегии",
    availableVersionFrom: "0.0",
    availableVersionTo: "99.99",
    platforms: [ "web" ],
    path: "",
  },
  {
    code: "iisWeb",
    id: 18,
    title: "ИИС",
    availableVersionFrom: "0.0",
    availableVersionTo: "99.99",
    platforms: [ "web" ],
    path: "",
  },
  {
    code: "zpifrWeb",
    id: 19,
    title: "ЗПИФ",
    availableVersionFrom: "0.0",
    availableVersionTo: "99.99",
    platforms: [ "web" ],
    path: "",
  },
  {
    code: "pensionWeb",
    id: 20,
    title: "Пенсии",
    availableVersionFrom: "0.0",
    availableVersionTo: "99.99",
    platforms: [ "web" ],
    path: "",
  },
  {
    code: "iszhWeb",
    id: 21,
    title: "ИСЖ",
    availableVersionFrom: "0.0",
    availableVersionTo: "99.99",
    platforms: [ "web" ],
    path: "",
  },
  {
    code: "brokerWeb",
    id: 22,
    title: "Брокерское обслуживание",
    availableVersionFrom: "0.0",
    availableVersionTo: "99.99",
    platforms: [ "web" ],
    path: "",
  },
]