export const PRODUCT = {
  INVESTMENTS_DASHBOARD: 'INVESTMENTS_DASHBOARD',
  PORTFOLIO_ANALYTICS: 'PORTFOLIO_ANALYTICS',
  PORTFOLIO_BALANCE: 'PORTFOLIO_BALANCE',
}

export const APP = {
  MOBILE: 'MOBILE',
  WEB: 'WEB',
}
