export const ADD_PLATFORM = "ADD_PLATFORM";
export const ADD_DEEPLINK = "ADD_DEEPLINK";
export const ADD_SCREEN = "ADD_SCREEN";
export const ADD_INTERNAL_SOURCE = "ADD_INTERNAL_SOURCE";
export const ADD_EXTERNAL_SOURCE = "ADD_EXTERNAL_SOURCE";
export const WEB_ACTIVE = "WEB_ACTIVE";
export const ADD_DEEPLINK_TYPE = "ADD_DEEPLINK_TYPE";
export const ADD_LINK = "ADD_LINK";