export const externalSources = [
    {code: "",             name: "Внутренний",     source: "", medium: ""},
    {code: "push_InvestPFM",         name: "Push",             },
    {code: "email_InvestPFM",        name: "E-mail",           },
    {code: "sms_InvestPFM",          name: "SMS",              },
    {code: "screensaver",  name: "Screensaver",      },
    {code: "zen",          name: "Яндекс.Дзен",      },
    {code: "fb",           name: "Facebook",         },
    {code: "vc",           name: "Вконтакте",        },
    {code: "twitter",      name: "Twitter",          },
    {code: "inst",         name: "Instagram",        },
    {code: "sberbank",     name: "Сайт Сбер Банка", medium: "site"},
    {code: "qr_vsp",       name: "QR-код в ВСП",    medium: "qr"},
    {code: "other",        name: "Другой (utm_source)"},
];